apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iris-sklearn-api
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: iris.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iris-sklearn-api
                port:
                  number: 80